version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build: ./src/api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: postgres_taskmg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mdmpereira
      POSTGRES_PASSWORD: nina
      POSTGRES_DB: taskmg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data:
