services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - JWT_SECRET_KEY
      - FRONTEND_URL
      - DATABASE_URL
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: postgres_taskmg
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mdmpereira -d taskmg"]
      interval: 5s
      retries: 5
    environment:
      - POSTGRES_USER=mdmpereira
      - POSTGRES_PASSWORD=nina
      - POSTGRES_DB=taskmg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
