# backend/Dockerfile
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    python3-dev \
    gcc \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get clean

COPY . .

EXPOSE 10000

ENV FLASK_ENV=production

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app", "--workers=4", "--timeout=120"]
