import os
import dotenv

DATABASE_URL = os.getenv("DATA_BASE_URL")
class Config:
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = DATABASE_URL
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    TEMPLATES_AUTO_RELOAD = True
